In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import pandas as pd
df= pd.read_csv('abc.csv')
df.head()

Unnamed: 0 Unnamed: 1     Unnamed: 2     Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0  Pregnancies    Glucose  BloodPressure  SkinThickness    Insulin        BMI   
1            6        148             72             35          0       33.6   
2            1         85             66             29          0       26.6   
3            8        183             64              0          0       23.3   
4            1         89             66             23         94       28.1   

                 Unnamed: 6 Unnamed: 7 Unnamed: 8  
0  DiabetesPedigreeFunction        Age    Outcome  
1                     0.627         50          1  
2                     0.351         31          0  
3                     0.672         32          1  
4                     0.167         21          0

In [ ]:
df.columns = df.iloc[0]
df = df.iloc[1: , :]
df.head()

0 Pregnancies Glucose BloodPressure SkinThickness Insulin   BMI  \
1           6     148            72            35       0  33.6   
2           1      85            66            29       0  26.6   
3           8     183            64             0       0  23.3   
4           1      89            66            23      94  28.1   
5           0     137            40            35     168  43.1   

0 DiabetesPedigreeFunction Age Outcome  
1                    0.627  50       1  
2                    0.351  31       0  
3                    0.672  32       1  
4                    0.167  21       0  
5                    2.288  33       1

In [ ]:
import numpy as np
df['Glucose']=np.where(df['Glucose']==0,df['Glucose'].median(),df['Glucose'])
df['Insulin']=np.where(df['Insulin']==0,df['Insulin'].median(),df['Insulin'])
df.head()

0 Pregnancies Glucose BloodPressure SkinThickness Insulin   BMI  \
1           6     148            72            35       0  33.6   
2           1      85            66            29       0  26.6   
3           8     183            64             0       0  23.3   
4           1      89            66            23      94  28.1   
5           0     137            40            35     168  43.1   

0 DiabetesPedigreeFunction Age Outcome  
1                    0.627  50       1  
2                    0.351  31       0  
3                    0.672  32       1  
4                    0.167  21       0  
5                    2.288  33       1

In [ ]:
X=df.drop('Outcome',axis=1)
y=df['Outcome']

In [ ]:
pd.DataFrame(X,columns=df.columns[:-1])

0   Pregnancies Glucose BloodPressure SkinThickness Insulin   BMI  \
1             6     148            72            35       0  33.6   
2             1      85            66            29       0  26.6   
3             8     183            64             0       0  23.3   
4             1      89            66            23      94  28.1   
5             0     137            40            35     168  43.1   
..          ...     ...           ...           ...     ...   ...   
764          10     101            76            48     180  32.9   
765           2     122            70            27       0  36.8   
766           5     121            72            23     112  26.2   
767           1     126            60             0       0  30.1   
768           1      93            70            31       0  30.4   

0   DiabetesPedigreeFunction Age  
1                      0.627  50  
2                      0.351  31  
3                      0.672  32  
4                      0.167  21  
5                      2.288  33  
..                       ...  ..  
764                    0.171  63  
765                     0.34  27  
766                    0.245  30  
767                    0.349  47  
768                    0.315  23  

[768 rows x 8 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=0)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=10).fit(X_train,y_train)
prediction = rf_classifier.predict(X_test)

In [ ]:
y.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,prediction))
print(accuracy_score(y_test,prediction))
print(classification_report(y_test,prediction))

[[91 16]
 [20 27]]
0.7662337662337663
              precision    recall  f1-score   support

           0       0.82      0.85      0.83       107
           1       0.63      0.57      0.60        47

    accuracy                           0.77       154
   macro avg       0.72      0.71      0.72       154
weighted avg       0.76      0.77      0.76       154



**MANUAL HYPERPARAMETER TUNING**

In [ ]:
model=RandomForestClassifier(n_estimators=300,criterion='entropy',
                             max_features='sqrt',min_samples_leaf=10,random_state=100).fit(X_train,y_train)
predictions=model.predict(X_test)
print(confusion_matrix(y_test,prediction))
print(accuracy_score(y_test,prediction))
print(classification_report(y_test,prediction))


[[91 16]
 [20 27]]
0.7662337662337663
              precision    recall  f1-score   support

           0       0.82      0.85      0.83       107
           1       0.63      0.57      0.60        47

    accuracy                           0.77       154
   macro avg       0.72      0.71      0.72       154
weighted avg       0.76      0.77      0.76       154



**RANDOMIZE SEARCH CV**

In [ ]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV

n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
max_features=['auto','sqrt','log2']
max_depth=[int(x) for x in np.linspace(10,1000,10)]
min_samples_split=[2,6,8,45]
min_samples_leaf=[1,5,3,2]
random_grid={'n_estimators': n_estimators,
             'max_features': max_features,
             'max_depth': max_depth,
             'min_samples_split': min_samples_split,
             'min_samples_leaf': min_samples_leaf,
             'criterion':['entropy','gini']}
print(random_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [2, 6, 8, 45], 'min_samples_leaf': [1, 5, 3, 2], 'criterion': ['entropy', 'gini']}


In [ ]:
rf=RandomForestClassifier()
rf_randomcv=RandomizedSearchCV(estimator=rf,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,
                               random_state=100,n_jobs=-1)
### fit the randomized model
rf_randomcv.fit(X_train,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 5, 3, 2],
                                        'min_samples_split': [2, 6, 8, 45],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=100, verbose=2)

In [ ]:
rf_randomcv.best_params_

{'criterion': 'gini',
 'max_depth': 1000,
 'max_features': 'sqrt',
 'min_samples_leaf': 1,
 'min_samples_split': 45,
 'n_estimators': 600}

In [ ]:
rf_randomcv

RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 5, 3, 2],
                                        'min_samples_split': [2, 6, 8, 45],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=100, verbose=2)

In [ ]:
best_random_grid=rf_randomcv.best_estimator_

In [ ]:
from sklearn.metrics import accuracy_score
y_pred=best_random_grid.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
print("Classification Report {}".format(classification_report(y_test,y_pred)))

[[97 10]
 [17 30]]
Accuracy Score 0.8246753246753247
Classification Report               precision    recall  f1-score   support

           0       0.85      0.91      0.88       107
           1       0.75      0.64      0.69        47

    accuracy                           0.82       154
   macro avg       0.80      0.77      0.78       154
weighted avg       0.82      0.82      0.82       154



**GRIDSEARCH CV**

In [ ]:
rf_randomcv.best_params_

{'criterion': 'gini',
 'max_depth': 1000,
 'max_features': 'sqrt',
 'min_samples_leaf': 1,
 'min_samples_split': 45,
 'n_estimators': 600}

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'criterion': [rf_randomcv.best_params_['criterion']],
    'max_depth': [rf_randomcv.best_params_['max_depth']],
    'max_features': [rf_randomcv.best_params_['max_features']],
    'min_samples_leaf': [rf_randomcv.best_params_['min_samples_leaf'], 
                         rf_randomcv.best_params_['min_samples_leaf']+2, 
                         rf_randomcv.best_params_['min_samples_leaf'] + 4],
    'min_samples_split': [rf_randomcv.best_params_['min_samples_split'] - 2,
                          rf_randomcv.best_params_['min_samples_split'] - 1,
                          rf_randomcv.best_params_['min_samples_split'], 
                          rf_randomcv.best_params_['min_samples_split'] +1,
                          rf_randomcv.best_params_['min_samples_split'] + 2],
    'n_estimators': [rf_randomcv.best_params_['n_estimators'] - 200, rf_randomcv.best_params_['n_estimators'] - 100, 
                     rf_randomcv.best_params_['n_estimators'], 
                     rf_randomcv.best_params_['n_estimators'] + 100, rf_randomcv.best_params_['n_estimators'] + 200]
}

print(param_grid)

{'criterion': ['gini'], 'max_depth': [1000], 'max_features': ['sqrt'], 'min_samples_leaf': [1, 3, 5], 'min_samples_split': [43, 44, 45, 46, 47], 'n_estimators': [400, 500, 600, 700, 800]}


In [ ]:
rf=RandomForestClassifier()
grid_search = GridSearchCV(estimator=rf,param_grid=param_grid,cv=10,n_jobs=-1,verbose=2)
grid_search.fit(X_train,y_train)

Fitting 10 folds for each of 75 candidates, totalling 750 fits


GridSearchCV(cv=10, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini'], 'max_depth': [1000],
                         'max_features': ['sqrt'],
                         'min_samples_leaf': [1, 3, 5],
                         'min_samples_split': [43, 44, 45, 46, 47],
                         'n_estimators': [400, 500, 600, 700, 800]},
             verbose=2)

In [ ]:
best_grid=grid_search.best_estimator_

In [ ]:
best_grid

RandomForestClassifier(max_depth=1000, max_features='sqrt', min_samples_leaf=3,
                       min_samples_split=45, n_estimators=400)

In [ ]:
y_pred=best_grid.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
print("Classification report: {}".format(classification_report(y_test,y_pred)))

[[98  9]
 [17 30]]
Accuracy Score 0.8311688311688312
Classification report:               precision    recall  f1-score   support

           0       0.85      0.92      0.88       107
           1       0.77      0.64      0.70        47

    accuracy                           0.83       154
   macro avg       0.81      0.78      0.79       154
weighted avg       0.83      0.83      0.83       154



Automated Hyperparameter Tuning **Bayesian Optimization**

In [ ]:
from hyperopt import hp,fmin,tpe,STATUS_OK,Trials

In [ ]:
space = {'criterion': hp.choice('criterion', ['entropy', 'gini']),
        'max_depth': hp.quniform('max_depth', 10, 1200, 10),
        'max_features': hp.choice('max_features', ['auto', 'sqrt','log2', None]),
        'min_samples_leaf': hp.uniform('min_samples_leaf', 0, 0.5),
        'min_samples_split' : hp.uniform ('min_samples_split', 0, 1),
        'n_estimators' : hp.choice('n_estimators', [10, 50, 300, 750, 1200,1300,1500])
    }

In [ ]:
space

{'criterion': <hyperopt.pyll.base.Apply at 0x7f8e9d6bbc10>,
 'max_depth': <hyperopt.pyll.base.Apply at 0x7f8e9d6bbb50>,
 'max_features': <hyperopt.pyll.base.Apply at 0x7f8e9d6bbf10>,
 'min_samples_leaf': <hyperopt.pyll.base.Apply at 0x7f8e9d6bb4d0>,
 'min_samples_split': <hyperopt.pyll.base.Apply at 0x7f8e9df01850>,
 'n_estimators': <hyperopt.pyll.base.Apply at 0x7f8e9d6acf10>}

In [ ]:
def objective(space):
    model = RandomForestClassifier(criterion = space['criterion'], max_depth = space['max_depth'],
                                 max_features = space['max_features'],
                                 min_samples_leaf = space['min_samples_leaf'],
                                 min_samples_split = space['min_samples_split'],
                                 n_estimators = space['n_estimators'], 
                                 )
    
    accuracy = cross_val_score(model, X_train, y_train, cv = 5).mean()

    # We aim to maximize accuracy, therefore we return it as a negative value
    return {'loss': -accuracy, 'status': STATUS_OK }

In [ ]:
from sklearn.model_selection import cross_val_score
trials= Trials()
best=fmin(fn=objective,
          space=space,
          algo=tpe.suggest,
          max_evals=80,
          trials=trials)

best

100%|██████████| 80/80 [08:20<00:00,  6.25s/it, best loss: -0.7703718512594963]


{'criterion': 1,
 'max_depth': 800.0,
 'max_features': 2,
 'min_samples_leaf': 0.02888016296109528,
 'min_samples_split': 0.20453564023138932,
 'n_estimators': 1}

In [ ]:
crit = {0: 'entropy', 1: 'gini'}
feat = {0: 'auto', 1: 'sqrt', 2: 'log2', 3: None}
est = {0: 10, 1: 50, 2: 300, 3: 750, 4: 1200,5:1300,6:1500}


print(crit[best['criterion']])
print(feat[best['max_features']])
print(est[best['n_estimators']])

gini
log2
50


In [ ]:
best['min_samples_leaf']


0.02888016296109528

In [ ]:
trainedforest = RandomForestClassifier(criterion = crit[best['criterion']], max_depth = best['max_depth'], 
                                       max_features = feat[best['max_features']], 
                                       min_samples_leaf = best['min_samples_leaf'], 
                                       min_samples_split = best['min_samples_split'], 
                                       n_estimators = est[best['n_estimators']]).fit(X_train,y_train)
predictionforest = trainedforest.predict(X_test)
print(confusion_matrix(y_test,predictionforest))
print(accuracy_score(y_test,predictionforest))
print(classification_report(y_test,predictionforest))
acc5 = accuracy_score(y_test,predictionforest)

[[98  9]
 [23 24]]
0.7922077922077922
              precision    recall  f1-score   support

           0       0.81      0.92      0.86       107
           1       0.73      0.51      0.60        47

    accuracy                           0.79       154
   macro avg       0.77      0.71      0.73       154
weighted avg       0.78      0.79      0.78       154

